[#3] 게시판 기능 구현
KTB-LuckyVicky/todayfin-be pull request #5
Opened 2024-08-05 15:47 UTC by chsjen492

## 🎯 기능 개요
- 게시판(커뮤니티) 기능 구현

## 🏗 구현 상세 및 설계 문서
- 게시판 CRUD
- 전체 뉴스 목록 페이징 추가
- 작성자 정보 확인을 위한 미들웨어 구현
- [API 설계](https://wide-hardhat-c5f.notion.site/API-bc1d966bf9e74a0fb6c42becb2851603?pvs=4)

## 🧪 테스트 계획 및 결과
- 테스트 코드 없음

## 🔍 사이드 이펙트 분석
- 사이드 이펙트 없음

## ✅ 체크리스트
- [x] 기능별 API 작성
- [x] API 테스트 확인

## 📝 추가 노트
- 에러 타입 추가 필요

2024-08-05 15:53 UTC, hyeong8465 approved these changes
무슨 뜻인지 정.확.히. 이해했습니다

2024-08-06 00:05 UTC, Nano2998 approved these changes
정확히 이해했습니다
(이해 잘 못함)

2024-08-06 00:11 UTC, s1lv3rrud requested changes

2024-08-06 00:11 UTC, s1lv3rrud commented on src/middlewares/community.ts
> +}
`verifyPostAuthor `함수의 로직이 이해가 안되어서 질문드립니다!  현재 로직은 해당 유저의 게시글이 한 개 이상 존재하면 next() 함수로 넘어가는 것으로 보이는데, 그렇다면 권한이 없는 게시글을 update 또는 delete 할 수 있게 되는 것이 아닐까요?🤔

2024-08-06 00:12 UTC, s1lv3rrud commented on src/middlewares/community.ts
> +}
request의 postId가 해당 유저의 게시글이 맞는지 확인하는 로직이 필요할 듯 싶습니다!

2024-08-06 00:16 UTC, chsjen492 commented on src/middlewares/community.ts
> +}
아 원래 해당 게시물을 작성한 유저인지를 판별해야 했는데 말씀해주신 내용대로 구현이 되어버렸네요!! 수정하겠습니당

2024-08-06 04:15 UTC, DS0708 approved these changes

2024-08-06 06:18 UTC, KDK-00 approved these changes
좋은코드입니다

2024-08-07 06:50 UTC, s1lv3rrud approved these changes
좋습니다!!! 다음 이슈도 파이팅~!

2024-08-07 06:50 UTC, s1lv3rrud commented on src/middlewares/community.ts
> +    const [rows] = await (await conn).query('select * from Post where _id=?', req.params.postId)
`select `문에서 `*` 대신 `authorId`만 가져와도 될 것 같아요~!
중요한건 아니니까 리팩토링하게되면 고쳐봐요💪

2024-08-07 07:00 UTC, merged